title: Coffee Shop
email: ddraskovv@gmail.com
description: ""
destination: docs
baseurl: "/coffee-shop"
url: "" 
github_username:  Draskovv
collections: 
  coffees:
    output: true
    permalink: /coffee/:path
  cakes:
    output: true
    permalink: /cakes/:path
collections_dir: collections


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package-lock.json
  - package.json
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
