
title: Coffee Shop
email: ddraskovv@gmail.com
description: HELLO THERE
baseurl: "/coffee-shop" 
url: "" 
twitter_username: draskovv
github_username:  draskovv

# Build settings
plugins:
  - jekyll-feed

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js

